apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  creationTimestamp: 2018-03-17T08:02:00Z
  generateName: heapster-
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster-zmtgd
  namespace: openshift-infra
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: heapster
    uid: 67e26c1f-29b9-11e8-85f2-fa163ee13785
  resourceVersion: "220322"
  selfLink: /api/v1/namespaces/openshift-infra/pods/heapster-zmtgd
  uid: 78c90613-29b9-11e8-85f2-fa163ee13785
spec:
  containers:
  - command:
    - heapster-wrapper.sh
    - --wrapper.allowed_users_file=/secrets/heapster.allowed-users
    - --source=kubernetes.summary_api:${MASTER_URL}?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
    - --tls_cert=/heapster-certs/tls.crt
    - --tls_key=/heapster-certs/tls.key
    - --tls_client_ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - --allowed_users=%allowed_users%
    - --metric_resolution=30s
    - --wrapper.username_file=/hawkular-account/hawkular-metrics.username
    - --wrapper.password_file=/hawkular-account/hawkular-metrics.password
    - --wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status
    - --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-metrics-certs/tls.crt&user=%username%&pass=%password%&filter=label(container_name:^system.slice.*|^user.slice)&concurrencyLimit=5
    env:
    - name: STARTUP_TIMEOUT
      value: "500"
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-heapster:v3.9
    imagePullPolicy: IfNotPresent
    name: heapster
    ports:
    - containerPort: 8082
      name: http-endpoint
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /opt/heapster-readiness.sh
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 3750M
      requests:
        memory: 937500k
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000040000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /secrets
      name: heapster-secrets
    - mountPath: /heapster-certs
      name: heapster-certs
    - mountPath: /hawkular-metrics-certs
      name: hawkular-metrics-certs
    - mountPath: /hawkular-account
      name: hawkular-metrics-account
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: heapster-token-w6k7b
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: heapster-dockercfg-pt4h8
  nodeName: 172.16.120.14
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000040000
    seLinuxOptions:
      level: s0:c6,c5
  serviceAccount: heapster
  serviceAccountName: heapster
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: heapster-secrets
    secret:
      defaultMode: 420
      secretName: heapster-secrets
  - name: heapster-certs
    secret:
      defaultMode: 420
      secretName: heapster-certs
  - name: hawkular-metrics-certs
    secret:
      defaultMode: 420
      secretName: hawkular-metrics-certs
  - name: hawkular-metrics-account
    secret:
      defaultMode: 420
      secretName: hawkular-metrics-account
  - name: heapster-token-w6k7b
    secret:
      defaultMode: 420
      secretName: heapster-token-w6k7b
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-17T08:02:00Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-17T08:03:22Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-17T08:02:00Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://712cfd202319d362ff5fcb6e10d74025b1b930ae9020d56a1bb72da679917964
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-heapster:v3.9
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-heapster@sha256:35ee16d7e26d451003e181e9a2da8656a9e90bc893e78c3a68a941a77a793be7
    lastState: {}
    name: heapster
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-17T08:02:03Z
  hostIP: 172.16.120.14
  phase: Running
  podIP: 10.128.0.68
  qosClass: Burstable
  startTime: 2018-03-17T08:02:00Z
