apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: pod-cpu-request
spec:
  reportingStart: '2018-01-01T00:00:00Z'
  reportingEnd: '2018-12-30T23:59:59Z'
  generationQuery: "pod-cpu-request"
  runImmediately: true
