apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"prometheus-node-exporter","role":"monitoring"},"name":"prometheus-node-exporter","namespace":"openshift-metrics"},"spec":{"template":{"metadata":{"labels":{"app":"prometheus-node-exporter","role":"monitoring"},"name":"prometheus-exporter"},"spec":{"containers":[{"image":"registry.access.redhat.com/openshift3/prometheus-node-exporter:v0.15.2","name":"node-exporter","ports":[{"containerPort":9100,"name":"scrape"}],"resources":{"limits":{"cpu":"200m","memory":"50Mi"},"requests":{"cpu":"100m","memory":"30Mi"}},"volumeMounts":[{"mountPath":"/host/proc","name":"proc","readOnly":true},{"mountPath":"/host/sys","name":"sys","readOnly":true}]}],"hostNetwork":true,"hostPID":true,"serviceAccountName":"prometheus-node-exporter","volumes":[{"hostPath":{"path":"/proc"},"name":"proc"},{"hostPath":{"path":"/sys"},"name":"sys"}]}},"updateStrategy":{"type":"RollingUpdate"}}}
  creationTimestamp: 2018-04-02T21:24:01Z
  generation: 1
  labels:
    app: prometheus-node-exporter
    role: monitoring
  name: prometheus-node-exporter
  namespace: openshift-metrics
  resourceVersion: "19001"
  selfLink: /apis/extensions/v1beta1/namespaces/openshift-metrics/daemonsets/prometheus-node-exporter
  uid: 299c4c0f-36bc-11e8-b543-fa163e332b7c
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-node-exporter
      role: monitoring
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-node-exporter
        role: monitoring
      name: prometheus-exporter
    spec:
      containers:
      - image: registry.access.redhat.com/openshift3/prometheus-node-exporter:v0.15.2
        imagePullPolicy: IfNotPresent
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-node-exporter
      serviceAccountName: prometheus-node-exporter
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
