apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"openshift-metrics","name":"prometheus","uid":"be6eef09-3388-11e8-a4fd-fa163e134ec8","apiVersion":"apps/v1beta1","resourceVersion":"137337"}}
    openshift.io/scc: restricted
  creationTimestamp: 2018-03-29T19:38:23Z
  generateName: prometheus-
  labels:
    app: prometheus
    controller-revision-hash: prometheus-4196452059
  name: prometheus-0
  namespace: openshift-metrics
  ownerReferences:
  - apiVersion: apps/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: prometheus
    uid: be6eef09-3388-11e8-a4fd-fa163e134ec8
  resourceVersion: "137401"
  selfLink: /api/v1/namespaces/openshift-metrics/pods/prometheus-0
  uid: be74a16a-3388-11e8-a4fd-fa163e134ec8
spec:
  containers:
  - args:
    - -provider=openshift
    - -https-address=:8443
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9090
    - -client-id=system:serviceaccount:openshift-metrics:prometheus
    - '-openshift-sar={"resource": "namespaces", "verb": "get", "resourceName": "openshift-metrics",
      "namespace": "openshift-metrics"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get", "resourceName":
      "openshift-metrics", "namespace": "openshift-metrics"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - -skip-auth-regex=^/metrics
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy:v3.7
    imagePullPolicy: IfNotPresent
    name: prom-proxy
    ports:
    - containerPort: 8443
      name: web
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000150000
      seLinuxOptions:
        level: s0:c12,c9
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/tls/private
      name: prometheus-tls
    - mountPath: /etc/proxy/secrets
      name: prometheus-secrets
    - mountPath: /prometheus
      name: prometheus-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-token-9v8q2
      readOnly: true
  - args:
    - --storage.tsdb.retention=6h
    - --storage.tsdb.min-block-duration=2m
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.listen-address=localhost:9090
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus:v3.7
    imagePullPolicy: IfNotPresent
    name: prometheus
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000150000
      seLinuxOptions:
        level: s0:c12,c9
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus
      name: prometheus-config
    - mountPath: /prometheus
      name: prometheus-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-token-9v8q2
      readOnly: true
  - args:
    - -provider=openshift
    - -https-address=:9443
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9099
    - -client-id=system:serviceaccount:openshift-metrics:prometheus
    - '-openshift-sar={"resource": "namespaces", "verb": "get", "resourceName": "openshift-metrics",
      "namespace": "openshift-metrics"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get", "resourceName":
      "openshift-metrics", "namespace": "openshift-metrics"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy:v3.7
    imagePullPolicy: IfNotPresent
    name: alerts-proxy
    ports:
    - containerPort: 9443
      name: web
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000150000
      seLinuxOptions:
        level: s0:c12,c9
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/tls/private
      name: alerts-tls
    - mountPath: /etc/proxy/secrets
      name: alerts-secrets
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-token-9v8q2
      readOnly: true
  - args:
    - --storage-path=/alert-buffer/messages.db
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus-alert-buffer:v3.7
    imagePullPolicy: IfNotPresent
    name: alert-buffer
    ports:
    - containerPort: 9099
      name: alert-buf
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000150000
      seLinuxOptions:
        level: s0:c12,c9
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /alert-buffer
      name: alert-buffer-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-token-9v8q2
      readOnly: true
  - args:
    - -config.file=/etc/alertmanager/alertmanager.yml
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus-alertmanager:v3.7
    imagePullPolicy: IfNotPresent
    name: alertmanager
    ports:
    - containerPort: 9093
      name: web
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000150000
      seLinuxOptions:
        level: s0:c12,c9
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/alertmanager
      name: alertmanager-config
    - mountPath: /alertmanager
      name: alertmanager-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-token-9v8q2
      readOnly: true
  dnsPolicy: ClusterFirst
  hostname: prometheus-0
  imagePullSecrets:
  - name: prometheus-dockercfg-cpj8l
  nodeName: 172.16.120.71
  nodeSelector:
    region: infra
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000150000
    seLinuxOptions:
      level: s0:c12,c9
  serviceAccount: prometheus
  serviceAccountName: prometheus
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      name: prometheus
    name: prometheus-config
  - name: prometheus-secrets
    secret:
      defaultMode: 420
      secretName: prometheus-proxy
  - name: prometheus-tls
    secret:
      defaultMode: 420
      secretName: prometheus-tls
  - name: prometheus-data
    persistentVolumeClaim:
      claimName: prometheus
  - configMap:
      defaultMode: 420
      name: prometheus-alerts
    name: alertmanager-config
  - name: alerts-secrets
    secret:
      defaultMode: 420
      secretName: alerts-proxy
  - name: alerts-tls
    secret:
      defaultMode: 420
      secretName: prometheus-alerts-tls
  - name: alertmanager-data
    persistentVolumeClaim:
      claimName: prometheus-alertmanager
  - name: alert-buffer-data
    persistentVolumeClaim:
      claimName: prometheus-alertbuffer
  - name: prometheus-token-9v8q2
    secret:
      defaultMode: 420
      secretName: prometheus-token-9v8q2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-29T19:38:23Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-29T19:38:38Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-29T19:38:23Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ef88a3e18416891db2d51a99eccf7f19524251a853de8817d8912ce153fd7063
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus-alert-buffer:v3.7
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus-alert-buffer@sha256:14675b8c9445e59541d07253cf1a8b6216e415f4cbdf1bede31bc28caf28fcad
    lastState: {}
    name: alert-buffer
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-29T19:38:37Z
  - containerID: docker://2acb4a637f20bd2b94f6a3ebafa70136ad45b1fc54a92c5e198b67f5a07da63b
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus-alertmanager:v3.7
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus-alertmanager@sha256:54d5afde4e0f356fddbaa7ade80c934f05a0e4944dd9df6b695b077a250489ba
    lastState: {}
    name: alertmanager
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-29T19:38:37Z
  - containerID: docker://e3ff24a34649eb6099e034d4bcebf10b111a39a178103d363676f7ac212f3b45
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy:v3.7
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy@sha256:7ef657e44d91d0c4553b14b563efaebe38a0250ecce1f00a3e597d3832c709ca
    lastState: {}
    name: alerts-proxy
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-29T19:38:36Z
  - containerID: docker://45a49a057fe42d52ed67cf3745fe6760c40d1acbf6a1c01591e596e06336df45
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy:v3.7
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy@sha256:7ef657e44d91d0c4553b14b563efaebe38a0250ecce1f00a3e597d3832c709ca
    lastState: {}
    name: prom-proxy
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-29T19:38:36Z
  - containerID: docker://fa3e426fa45a74195a6e4037d552cf38e1d82da095ff521042f51a348af2ad23
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus:v3.7
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/prometheus@sha256:286f79647be0d997856639d1ade079e567d753d33feaa22f530fd4fabe755afb
    lastState: {}
    name: prometheus
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-29T19:38:36Z
  hostIP: 172.16.120.71
  phase: Running
  podIP: 10.128.0.35
  qosClass: BestEffort
  startTime: 2018-03-29T19:38:23Z
