apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: logging-kibana-ops
    openshift.io/deployment.name: logging-kibana-ops-1
    openshift.io/scc: restricted
  creationTimestamp: 2018-03-13T23:14:39Z
  generateName: logging-kibana-ops-1-
  labels:
    component: kibana-ops
    deployment: logging-kibana-ops-1
    deploymentconfig: logging-kibana-ops
    logging-infra: kibana
    provider: openshift
  name: logging-kibana-ops-1-v299t
  namespace: qs61r
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: logging-kibana-ops-1
    uid: 4ac281fa-2714-11e8-bf7f-fa163eae21aa
  resourceVersion: "37266"
  selfLink: /api/v1/namespaces/qs61r/pods/logging-kibana-ops-1-v299t
  uid: 4e2e315a-2714-11e8-bf7f-fa163eae21aa
spec:
  containers:
  - env:
    - name: ES_HOST
      value: logging-es-ops
    - name: ES_PORT
      value: "9200"
    - name: KIBANA_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: kibana
          divisor: "0"
          resource: limits.memory
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-kibana:v3.9
    imagePullPolicy: IfNotPresent
    name: kibana
    readinessProbe:
      exec:
        command:
        - /usr/share/kibana/probe/readiness.sh
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000120000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kibana/keys
      name: kibana
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-kibana-token-kbxmb
      readOnly: true
  - env:
    - name: OAP_BACKEND_URL
      value: http://localhost:5601
    - name: OAP_AUTH_MODE
      value: oauth2
    - name: OAP_TRANSFORM
      value: user_header,token_header
    - name: OAP_OAUTH_ID
      value: kibana-proxy
    - name: OAP_MASTER_URL
      value: https://kubernetes.default.svc.cluster.local
    - name: OAP_PUBLIC_MASTER_URL
      value: https://aos-132.lab.sjc.redhat.com:8443
    - name: OAP_LOGOUT_REDIRECT
      value: https://aos-132.lab.sjc.redhat.com:8443/console/logout
    - name: OAP_MASTER_CA_FILE
      value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - name: OAP_DEBUG
      value: "False"
    - name: OAP_OAUTH_SECRET_FILE
      value: /secret/oauth-secret
    - name: OAP_SERVER_CERT_FILE
      value: /secret/server-cert
    - name: OAP_SERVER_KEY_FILE
      value: /secret/server-key
    - name: OAP_SERVER_TLS_FILE
      value: /secret/server-tls.json
    - name: OAP_SESSION_SECRET_FILE
      value: /secret/session-secret
    - name: OCP_AUTH_PROXY_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: kibana-proxy
          divisor: "0"
          resource: limits.memory
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-auth-proxy:v3.9
    imagePullPolicy: IfNotPresent
    name: kibana-proxy
    ports:
    - containerPort: 3000
      name: oaproxy
      protocol: TCP
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000120000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /secret
      name: kibana-proxy
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: aggregated-logging-kibana-token-kbxmb
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: aggregated-logging-kibana-dockercfg-mt6xj
  nodeName: 192.168.100.6
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000120000
    seLinuxOptions:
      level: s0:c11,c5
  serviceAccount: aggregated-logging-kibana
  serviceAccountName: aggregated-logging-kibana
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kibana
    secret:
      defaultMode: 420
      secretName: logging-kibana
  - name: kibana-proxy
    secret:
      defaultMode: 420
      secretName: logging-kibana-proxy
  - name: aggregated-logging-kibana-token-kbxmb
    secret:
      defaultMode: 420
      secretName: aggregated-logging-kibana-token-kbxmb
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T23:14:39Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T23:15:04Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T23:14:39Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://15692afaa40205212b880aab6d438e5ff96c4f5214e28d57b4253b695d741c50
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-kibana:v3.9
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-kibana@sha256:d45f19b4b55dc9ac26ed661f4148536042c9522ca7d850dd5273a56dde7d1f52
    lastState: {}
    name: kibana
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-13T23:14:44Z
  - containerID: docker://ce34fe3badbe735b2f27f80966e86a54295cfd0d39ace6206e31a1b7ca31ad59
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-auth-proxy:v3.9
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-auth-proxy@sha256:cc3a01c1409381135c9edfb1f87ac1780f25b4d39f8da25248d0265bb03e1cfc
    lastState: {}
    name: kibana-proxy
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-13T23:14:46Z
  hostIP: 192.168.100.6
  phase: Running
  podIP: 10.129.0.21
  qosClass: Burstable
  startTime: 2018-03-13T23:14:39Z
