apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"openshift-infra","name":"hawkular-cassandra-1","uid":"831922cf-2961-11e8-add0-fa163e40c339","apiVersion":"v1","resourceVersion":"202546"}}
    openshift.io/scc: restricted
  creationTimestamp: 2018-03-16T21:51:25Z
  generateName: hawkular-cassandra-1-
  labels:
    metrics-infra: hawkular-cassandra
    name: hawkular-cassandra-1
    type: hawkular-cassandra
  name: hawkular-cassandra-1-rdzqp
  namespace: openshift-infra
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: hawkular-cassandra-1
    uid: 831922cf-2961-11e8-add0-fa163e40c339
  resourceVersion: "202651"
  selfLink: /api/v1/namespaces/openshift-infra/pods/hawkular-cassandra-1-rdzqp
  uid: 2c6b3339-2964-11e8-add0-fa163e40c339
spec:
  containers:
  - command:
    - /opt/apache-cassandra/bin/cassandra-docker.sh
    - --cluster_name=hawkular-metrics
    - --data_volume=/cassandra_data
    - --internode_encryption=all
    - --require_node_auth=true
    - --enable_client_encryption=true
    - --require_client_auth=true
    env:
    - name: CASSANDRA_MASTER
      value: "true"
    - name: CASSANDRA_DATA_VOLUME
      value: /cassandra_data
    - name: JVM_OPTS
      value: -Dcassandra.commitlog.ignorereplayerrors=true
    - name: ENABLE_PROMETHEUS_ENDPOINT
      value: "True"
    - name: TRUSTSTORE_NODES_AUTHORITIES
      value: /hawkular-cassandra-certs/tls.peer.truststore.crt
    - name: TRUSTSTORE_CLIENT_AUTHORITIES
      value: /hawkular-cassandra-certs/tls.client.truststore.crt
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: 1m
          resource: limits.cpu
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-cassandra:v3.7
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - /opt/apache-cassandra/bin/cassandra-poststart.sh
      preStop:
        exec:
          command:
          - /opt/apache-cassandra/bin/cassandra-prestop.sh
    name: hawkular-cassandra-1
    ports:
    - containerPort: 9042
      name: cql-port
      protocol: TCP
    - containerPort: 9160
      name: thift-port
      protocol: TCP
    - containerPort: 7000
      name: tcp-port
      protocol: TCP
    - containerPort: 7001
      name: ssl-port
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /opt/apache-cassandra/bin/cassandra-docker-ready.sh
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 2G
      requests:
        memory: 1G
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000040000
      seLinuxOptions:
        level: s0:c6,c5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cassandra_data
      name: cassandra-data
    - mountPath: /hawkular-cassandra-certs
      name: hawkular-cassandra-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: cassandra-token-hq8th
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: cassandra-dockercfg-ngvx6
  nodeName: 172.16.120.21
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000040000
    seLinuxOptions:
      level: s0:c6,c5
    supplementalGroups:
    - 65531
  serviceAccount: cassandra
  serviceAccountName: cassandra
  terminationGracePeriodSeconds: 1800
  volumes:
  - emptyDir: {}
    name: cassandra-data
  - name: hawkular-cassandra-certs
    secret:
      defaultMode: 420
      secretName: hawkular-cassandra-certs
  - name: cassandra-token-hq8th
    secret:
      defaultMode: 420
      secretName: cassandra-token-hq8th
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-16T21:51:25Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-16T21:51:46Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-16T21:51:25Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c99b880a965af5196b68f28b293f3a7c808b8bccf15e9a1f9347c1384a9a1048
    image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-cassandra:v3.7
    imageID: docker-pullable://brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-cassandra@sha256:58fd35b22d4d48f30ed314cfb05617c38ac0671e0351b4fd77f1c20521cebeb3
    lastState: {}
    name: hawkular-cassandra-1
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-16T21:51:27Z
  hostIP: 172.16.120.21
  phase: Running
  podIP: 10.128.0.63
  qosClass: Burstable
  startTime: 2018-03-16T21:51:25Z

