apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2018-04-10T22:47:06Z
  generation: 2
  labels:
    component: es-ops
    deployment: logging-es-ops-data-master-bsjwj95b
    logging-infra: elasticsearch
    provider: openshift
  name: logging-es-ops-data-master-bsjwj95b
  namespace: ld4wp
  resourceVersion: "236109"
  selfLink: /apis/apps.openshift.io/v1/namespaces/ld4wp/deploymentconfigs/logging-es-ops-data-master-bsjwj95b
  uid: 18441393-3d11-11e8-9c5f-fa163ec882f7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    component: es-ops
    deployment: logging-es-ops-data-master-bsjwj95b
    logging-infra: elasticsearch
    provider: openshift
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: es-ops
        deployment: logging-es-ops-data-master-bsjwj95b
        logging-infra: elasticsearch
        provider: openshift
      name: logging-es-ops-data-master-bsjwj95b
    spec:
      containers:
      - env:
        - name: DC_NAME
          value: logging-es-ops-data-master-bsjwj95b
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: SERVICE_DNS
          value: logging-es-ops-cluster
        - name: CLUSTER_NAME
          value: logging-es-ops
        - name: INSTANCE_RAM
          value: 512Mi
        - name: HEAP_DUMP_LOCATION
          value: /elasticsearch/persistent/heapdump.hprof
        - name: NODE_QUORUM
          value: "1"
        - name: RECOVER_EXPECTED_NODES
          value: "1"
        - name: RECOVER_AFTER_TIME
          value: 5m
        - name: READINESS_PROBE_TIMEOUT
          value: "30"
        - name: POD_LABEL
          value: component=es-ops
        - name: IS_MASTER
          value: "true"
        - name: HAS_DATA
          value: "true"
        - name: PROMETHEUS_USER
          value: system:serviceaccount:openshift-metrics:prometheus
        image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-elasticsearch:v3.9
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: restapi
          protocol: TCP
        - containerPort: 9300
          name: cluster
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/share/java/elasticsearch/probe/readiness.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/elasticsearch/secret
          name: elasticsearch
          readOnly: true
        - mountPath: /usr/share/java/elasticsearch/config
          name: elasticsearch-config
          readOnly: true
        - mountPath: /elasticsearch/persistent
          name: elasticsearch-storage
      - args:
        - --upstream-ca=/etc/elasticsearch/secret/admin-ca
        - --https-address=:4443
        - -provider=openshift
        - -client-id=system:serviceaccount:ld4wp:aggregated-logging-elasticsearch
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -cookie-secret=N2FGalNOQTlvTkZUMHBIdg==
        - -basic-auth-password=5FrFUPPgJcl2GLgM
        - -upstream=https://localhost:9200
        - '-openshift-sar={"namespace": "ld4wp", "verb": "view", "resource": "prometheus",
          "group": "metrics.openshift.io"}'
        - '-openshift-delegate-urls={"/": {"resource": "prometheus", "verb": "view",
          "group": "metrics.openshift.io", "namespace": "ld4wp"}}'
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - -pass-access-token
        - -pass-user-headers
        image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/oauth-proxy:v3.9
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 4443
          name: proxy
          protocol: TCP
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls
          readOnly: true
        - mountPath: /etc/elasticsearch/secret
          name: elasticsearch
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 65534
      serviceAccount: aggregated-logging-elasticsearch
      serviceAccountName: aggregated-logging-elasticsearch
      terminationGracePeriodSeconds: 30
      volumes:
      - name: proxy-tls
        secret:
          defaultMode: 420
          secretName: prometheus-tls
      - name: elasticsearch
        secret:
          defaultMode: 420
          secretName: logging-elasticsearch
      - configMap:
          defaultMode: 420
          name: logging-elasticsearch
        name: elasticsearch-config
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: foo-ops--0
  test: false
  triggers: []
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-04-10T22:53:48Z
    lastUpdateTime: 2018-04-10T22:53:48Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-04-10T22:53:49Z
    lastUpdateTime: 2018-04-10T22:53:49Z
    message: replication controller "logging-es-ops-data-master-bsjwj95b-1" successfully
      rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: Manual
    message: manual change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
