apiVersion: v1
items:
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    annotations:
      autoscaling.openshift.io/machineautoscaler: openshift-machine-api/qe-pruan-09-25-072823-g85zs-worker-us-west-1a
      machine.openshift.io/cluster-api-autoscaler-node-group-max-size: "10"
      machine.openshift.io/cluster-api-autoscaler-node-group-min-size: "1"
    creationTimestamp: "2019-09-25T17:27:01Z"
    generation: 2
    labels:
      machine.openshift.io/cluster-api-cluster: qe-pruan-09-25-072823-g85zs
    name: qe-pruan-09-25-072823-g85zs-worker-us-west-1a
    namespace: openshift-machine-api
    resourceVersion: "46183"
    selfLink: /apis/machine.openshift.io/v1beta1/namespaces/openshift-machine-api/machinesets/qe-pruan-09-25-072823-g85zs-worker-us-west-1a
    uid: af79c768-dfb9-11e9-855b-0265d977e269
  spec:
    replicas: 3
    selector:
      matchLabels:
        machine.openshift.io/cluster-api-cluster: qe-pruan-09-25-072823-g85zs
        machine.openshift.io/cluster-api-machineset: qe-pruan-09-25-072823-g85zs-worker-us-west-1a
    template:
      metadata:
        creationTimestamp: null
        labels:
          machine.openshift.io/cluster-api-cluster: qe-pruan-09-25-072823-g85zs
          machine.openshift.io/cluster-api-machine-role: worker
          machine.openshift.io/cluster-api-machine-type: worker
          machine.openshift.io/cluster-api-machineset: qe-pruan-09-25-072823-g85zs-worker-us-west-1a
      spec:
        metadata:
          creationTimestamp: null
        providerSpec:
          value:
            ami:
              id: ami-0b7932f135cd74eea
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
            credentialsSecret:
              name: aws-cloud-credentials
            deviceIndex: 0
            iamInstanceProfile:
              id: qe-pruan-09-25-072823-g85zs-worker-profile
            instanceType: m5.xlarge
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: us-west-1a
              region: us-west-1
            publicIp: null
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - qe-pruan-09-25-072823-g85zs-worker-sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - qe-pruan-09-25-072823-g85zs-private-us-west-1a
            tags:
            - name: kubernetes.io/cluster/qe-pruan-09-25-072823-g85zs
              value: owned
            userDataSecret:
              name: worker-user-data
  status:
    availableReplicas: 3
    fullyLabeledReplicas: 3
    observedGeneration: 2
    readyReplicas: 3
    replicas: 3
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    annotations:
      autoscaling.openshift.io/machineautoscaler: openshift-machine-api/qe-pruan-09-25-072823-g85zs-worker-us-west-1c
      machine.openshift.io/cluster-api-autoscaler-node-group-max-size: "10"
      machine.openshift.io/cluster-api-autoscaler-node-group-min-size: "1"
    creationTimestamp: "2019-09-25T17:27:02Z"
    generation: 1
    labels:
      machine.openshift.io/cluster-api-cluster: qe-pruan-09-25-072823-g85zs
    name: qe-pruan-09-25-072823-g85zs-worker-us-west-1c
    namespace: openshift-machine-api
    resourceVersion: "44275"
    selfLink: /apis/machine.openshift.io/v1beta1/namespaces/openshift-machine-api/machinesets/qe-pruan-09-25-072823-g85zs-worker-us-west-1c
    uid: afaac740-dfb9-11e9-855b-0265d977e269
  spec:
    replicas: 1
    selector:
      matchLabels:
        machine.openshift.io/cluster-api-cluster: qe-pruan-09-25-072823-g85zs
        machine.openshift.io/cluster-api-machineset: qe-pruan-09-25-072823-g85zs-worker-us-west-1c
    template:
      metadata:
        creationTimestamp: null
        labels:
          machine.openshift.io/cluster-api-cluster: qe-pruan-09-25-072823-g85zs
          machine.openshift.io/cluster-api-machine-role: worker
          machine.openshift.io/cluster-api-machine-type: worker
          machine.openshift.io/cluster-api-machineset: qe-pruan-09-25-072823-g85zs-worker-us-west-1c
      spec:
        metadata:
          creationTimestamp: null
        providerSpec:
          value:
            ami:
              id: ami-0b7932f135cd74eea
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
            credentialsSecret:
              name: aws-cloud-credentials
            deviceIndex: 0
            iamInstanceProfile:
              id: qe-pruan-09-25-072823-g85zs-worker-profile
            instanceType: m5.xlarge
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: us-west-1c
              region: us-west-1
            publicIp: null
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - qe-pruan-09-25-072823-g85zs-worker-sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - qe-pruan-09-25-072823-g85zs-private-us-west-1c
            tags:
            - name: kubernetes.io/cluster/qe-pruan-09-25-072823-g85zs
              value: owned
            userDataSecret:
              name: worker-user-data
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
