apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"creationTimestamp":"2018-03-16T21:32:22Z","generation":3,"labels":{"metrics-infra":"hawkular-cassandra","name":"hawkular-cassandra","type":"hawkular-cassandra"},"name":"hawkular-cassandra-1","namespace":"openshift-infra","selfLink":"/api/v1/namespaces/openshift-infra/replicationcontrollers/hawkular-cassandra-1","uid":"831922cf-2961-11e8-add0-fa163e40c339"},"spec":{"replicas":1,"selector":{"name":"hawkular-cassandra-1"},"template":{"metadata":{"creationTimestamp":null,"labels":{"metrics-infra":"hawkular-cassandra","name":"hawkular-cassandra-1","type":"hawkular-cassandra"}},"spec":{"containers":[{"command":["/opt/apache-cassandra/bin/cassandra-docker.sh","--cluster_name=hawkular-metrics","--data_volume=/cassandra_data","--internode_encryption=all","--require_node_auth=true","--enable_client_encryption=true","--require_client_auth=true"],"env":[{"name":"CASSANDRA_MASTER","value":"true"},{"name":"CASSANDRA_DATA_VOLUME","value":"/cassandra_data"},{"name":"JVM_OPTS","value":"-Dcassandra.commitlog.ignorereplayerrors=true"},{"name":"ENABLE_PROMETHEUS_ENDPOINT","value":"True"},{"name":"TRUSTSTORE_NODES_AUTHORITIES","value":"/hawkular-cassandra-certs/tls.peer.truststore.crt"},{"name":"TRUSTSTORE_CLIENT_AUTHORITIES","value":"/hawkular-cassandra-certs/tls.client.truststore.crt"},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"limits.memory"}}},{"name":"CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1m","resource":"limits.cpu"}}}],"image":"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-cassandra:v3.7","imagePullPolicy":"IfNotPresent","lifecycle":{"postStart":{"exec":{"command":["/opt/apache-cassandra/bin/cassandra-poststart.sh"]}},"preStop":{"exec":{"command":["/opt/apache-cassandra/bin/cassandra-prestop.sh"]}}},"name":"hawkular-cassandra-1","ports":[{"containerPort":9042,"name":"cql-port","protocol":"TCP"},{"containerPort":9160,"name":"thift-port","protocol":"TCP"},{"containerPort":7000,"name":"tcp-port","protocol":"TCP"},{"containerPort":7001,"name":"ssl-port","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["/opt/apache-cassandra/bin/cassandra-docker-ready.sh"]},"failureThreshold":3,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"memory":"2G"},"requests":{"memory":"1G"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cassandra_data","name":"cassandra-data"},{"mountPath":"/hawkular-cassandra-certs","name":"hawkular-cassandra-certs"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"supplementalGroups":[65531]},"serviceAccount":"cassandra","serviceAccountName":"cassandra","terminationGracePeriodSeconds":1800,"volumes":[{"emptyDir":{},"name":"cassandra-data"},{"name":"hawkular-cassandra-certs","secret":{"defaultMode":420,"secretName":"hawkular-cassandra-certs"}}]}}},"status":{"observedGeneration":3,"replicas":0}}
  creationTimestamp: 2018-03-16T21:32:22Z
  generation: 4
  labels:
    metrics-infra: hawkular-cassandra
    name: hawkular-cassandra
    type: hawkular-cassandra
  name: hawkular-cassandra-1
  namespace: openshift-infra
  resourceVersion: "202652"
  selfLink: /api/v1/namespaces/openshift-infra/replicationcontrollers/hawkular-cassandra-1
  uid: 831922cf-2961-11e8-add0-fa163e40c339
spec:
  replicas: 1
  selector:
    name: hawkular-cassandra-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        metrics-infra: hawkular-cassandra
        name: hawkular-cassandra-1
        type: hawkular-cassandra
    spec:
      containers:
      - command:
        - /opt/apache-cassandra/bin/cassandra-docker.sh
        - --cluster_name=hawkular-metrics
        - --data_volume=/cassandra_data
        - --internode_encryption=all
        - --require_node_auth=true
        - --enable_client_encryption=true
        - --require_client_auth=true
        env:
        - name: CASSANDRA_MASTER
          value: "true"
        - name: CASSANDRA_DATA_VOLUME
          value: /cassandra_data
        - name: JVM_OPTS
          value: -Dcassandra.commitlog.ignorereplayerrors=true
        - name: ENABLE_PROMETHEUS_ENDPOINT
          value: "True"
        - name: TRUSTSTORE_NODES_AUTHORITIES
          value: /hawkular-cassandra-certs/tls.peer.truststore.crt
        - name: TRUSTSTORE_CLIENT_AUTHORITIES
          value: /hawkular-cassandra-certs/tls.client.truststore.crt
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: 1m
              resource: limits.cpu
        image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-cassandra:v3.7
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - /opt/apache-cassandra/bin/cassandra-poststart.sh
          preStop:
            exec:
              command:
              - /opt/apache-cassandra/bin/cassandra-prestop.sh
        name: hawkular-cassandra-1
        ports:
        - containerPort: 9042
          name: cql-port
          protocol: TCP
        - containerPort: 9160
          name: thift-port
          protocol: TCP
        - containerPort: 7000
          name: tcp-port
          protocol: TCP
        - containerPort: 7001
          name: ssl-port
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/apache-cassandra/bin/cassandra-docker-ready.sh
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 2G
          requests:
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cassandra_data
          name: cassandra-data
        - mountPath: /hawkular-cassandra-certs
          name: hawkular-cassandra-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 65531
      serviceAccount: cassandra
      serviceAccountName: cassandra
      terminationGracePeriodSeconds: 1800
      volumes:
      - emptyDir: {}
        name: cassandra-data
      - name: hawkular-cassandra-certs
        secret:
          defaultMode: 420
          secretName: hawkular-cassandra-certs
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1

