apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"creationTimestamp":"2018-03-17T08:01:32Z","generation":2,"labels":{"metrics-infra":"heapster","name":"heapster"},"name":"heapster","namespace":"openshift-infra","selfLink":"/api/v1/namespaces/openshift-infra/replicationcontrollers/heapster","uid":"67e26c1f-29b9-11e8-85f2-fa163ee13785"},"spec":{"replicas":1,"selector":{"name":"heapster"},"template":{"metadata":{"creationTimestamp":null,"labels":{"metrics-infra":"heapster","name":"heapster"},"name":"heapster"},"spec":{"containers":[{"command":["heapster-wrapper.sh","--wrapper.allowed_users_file=/secrets/heapster.allowed-users","--source=kubernetes.summary_api:${MASTER_URL}?useServiceAccount=true\u0026kubeletHttps=true\u0026kubeletPort=10250","--tls_cert=/heapster-certs/tls.crt","--tls_key=/heapster-certs/tls.key","--tls_client_ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt","--allowed_users=%allowed_users%","--metric_resolution=30s","--wrapper.username_file=/hawkular-account/hawkular-metrics.username","--wrapper.password_file=/hawkular-account/hawkular-metrics.password","--wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status","--sink=hawkular:https://hawkular-metrics:443?tenant=_system\u0026labelToTenant=pod_namespace\u0026labelNodeId=nodename\u0026caCert=/hawkular-metrics-certs/tls.crt\u0026user=%username%\u0026pass=%password%\u0026filter=label(container_name:^system.slice.*|^user.slice)\u0026concurrencyLimit=5"],"env":[{"name":"STARTUP_TIMEOUT","value":"500"}],"image":"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-heapster:v3.9","imagePullPolicy":"IfNotPresent","name":"heapster","ports":[{"containerPort":8082,"name":"http-endpoint","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["/opt/heapster-readiness.sh"]},"failureThreshold":3,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"memory":"3750M"},"requests":{"memory":"937500k"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/secrets","name":"heapster-secrets"},{"mountPath":"/heapster-certs","name":"heapster-certs"},{"mountPath":"/hawkular-metrics-certs","name":"hawkular-metrics-certs"},{"mountPath":"/hawkular-account","name":"hawkular-metrics-account"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"heapster","serviceAccountName":"heapster","terminationGracePeriodSeconds":30,"volumes":[{"name":"heapster-secrets","secret":{"defaultMode":420,"secretName":"heapster-secrets"}},{"name":"heapster-certs","secret":{"defaultMode":420,"secretName":"heapster-certs"}},{"name":"hawkular-metrics-certs","secret":{"defaultMode":420,"secretName":"hawkular-metrics-certs"}},{"name":"hawkular-metrics-account","secret":{"defaultMode":420,"secretName":"hawkular-metrics-account"}}]}}},"status":{"observedGeneration":2,"replicas":0}}
  creationTimestamp: 2018-03-17T08:01:32Z
  generation: 3
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster
  namespace: openshift-infra
  resourceVersion: "220324"
  selfLink: /api/v1/namespaces/openshift-infra/replicationcontrollers/heapster
  uid: 67e26c1f-29b9-11e8-85f2-fa163ee13785
spec:
  replicas: 1
  selector:
    name: heapster
  template:
    metadata:
      creationTimestamp: null
      labels:
        metrics-infra: heapster
        name: heapster
      name: heapster
    spec:
      containers:
      - command:
        - heapster-wrapper.sh
        - --wrapper.allowed_users_file=/secrets/heapster.allowed-users
        - --source=kubernetes.summary_api:${MASTER_URL}?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
        - --tls_cert=/heapster-certs/tls.crt
        - --tls_key=/heapster-certs/tls.key
        - --tls_client_ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --allowed_users=%allowed_users%
        - --metric_resolution=30s
        - --wrapper.username_file=/hawkular-account/hawkular-metrics.username
        - --wrapper.password_file=/hawkular-account/hawkular-metrics.password
        - --wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status
        - --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-metrics-certs/tls.crt&user=%username%&pass=%password%&filter=label(container_name:^system.slice.*|^user.slice)&concurrencyLimit=5
        env:
        - name: STARTUP_TIMEOUT
          value: "500"
        image: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/metrics-heapster:v3.9
        imagePullPolicy: IfNotPresent
        name: heapster
        ports:
        - containerPort: 8082
          name: http-endpoint
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/heapster-readiness.sh
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 3750M
          requests:
            memory: 937500k
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: heapster-secrets
        - mountPath: /heapster-certs
          name: heapster-certs
        - mountPath: /hawkular-metrics-certs
          name: hawkular-metrics-certs
        - mountPath: /hawkular-account
          name: hawkular-metrics-account
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: heapster
      serviceAccountName: heapster
      terminationGracePeriodSeconds: 30
      volumes:
      - name: heapster-secrets
        secret:
          defaultMode: 420
          secretName: heapster-secrets
      - name: heapster-certs
        secret:
          defaultMode: 420
          secretName: heapster-certs
      - name: hawkular-metrics-certs
        secret:
          defaultMode: 420
          secretName: hawkular-metrics-certs
      - name: hawkular-metrics-account
        secret:
          defaultMode: 420
          secretName: hawkular-metrics-account
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
