apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: privileged
    creationTimestamp: 2018-03-13T23:02:53Z
    labels:
      name: base-ansible-pod
    name: base-ansible-pod
    namespace: qs61r
    resourceVersion: "36051"
    selfLink: /api/v1/namespaces/qs61r/pods/base-ansible-pod
    uid: a90e57c3-2712-11e8-bf7f-fa163eae21aa
  spec:
    containers:
    - image: aosqe/fedora_base
      imagePullPolicy: Always
      name: base-ansible-pod
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-qtq2n
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-qqsww
    nodeName: 192.168.100.25
    nodeSelector:
      node-role.kubernetes.io/compute: "true"
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: default-token-qtq2n
      secret:
        defaultMode: 420
        secretName: default-token-qtq2n
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-03-13T23:02:53Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-03-13T23:03:05Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-03-13T23:02:53Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://e021564b728bcb74da6e3a1a99f00869cd68fc856a182157ddf908b8eff0b848
      image: docker.io/aosqe/fedora_base:latest
      imageID: docker-pullable://docker.io/aosqe/fedora_base@sha256:3c6cf5f5f189838f7f48c32fe3557f272fb500fb99f00a1b00a3b0d3b80517a4
      lastState: {}
      name: base-ansible-pod
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-03-13T23:03:05Z
    hostIP: 192.168.100.25
    phase: Running
    podIP: 10.128.0.15
    qosClass: BestEffort
    startTime: 2018-03-13T23:02:53Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

